services:
  db:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bookshop_database
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "1542:80"
    networks:
      - postgres-compose-network
    depends_on:
      - db

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  postgres_data:
